# Generated by Django 5.1.4 on 2025-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
