# Generated by Django 5.1.4 on 2025-04-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
