# Generated by Django 5.1.4 on 2025-04-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0004_roles_users_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
