# Generated by Django 5.1.4 on 2025-04-18 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0005_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='TotalScores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='TotalWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('menS', "Men's Singles"), ('menD', "Men's Doubles"), ('womS', "Women's Singles"), ('womD', "Women's Doubles")], default='menS', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='TotalScores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='TotalWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('organizer', 'Organizer'), ('referee', 'Referee')], default='player', max_length=10),
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='bmclub.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='bmclub.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmclub.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playermatches_won', to='bmclub.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='bmclub.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='bmclub.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmclub.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammatches_won', to='bmclub.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
