# Generated by Django 5.1.4 on 2025-04-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0006_player_totalscores_player_totalwins_player_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='player1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='player2Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team1Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team2Score',
            field=models.IntegerField(default=0),
        ),
    ]
