# Generated by Django 5.1.4 on 2025-04-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0009_playermatch_ref_teammatch_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatch',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='winner',
        ),
        migrations.AddField(
            model_name='playermatch',
            name='player1wins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playermatches_won1', to='bmclub.player'),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='player2wins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playermatches_won2', to='bmclub.player'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team1wins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammatches_won1', to='bmclub.team'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team2wins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammatches_won2', to='bmclub.team'),
        ),
    ]
