# Generated by Django 5.1.4 on 2025-04-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0010_remove_playermatch_winner_remove_teammatch_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team2player1', to='bmclub.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team2player2', to='bmclub.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2teamxyz', to='bmclub.team'),
        ),
    ]
