# Generated by Django 5.1.4 on 2025-04-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0011_team_player1_team_player2_alter_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player2',
        ),
    ]
