# Generated by Django 5.1.4 on 2025-04-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0014_alter_teammatch_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
