# Generated by Django 5.1.4 on 2025-04-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0015_playermatch_duration_teammatch_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatch',
            name='player1wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatch',
            name='player2wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammatch',
            name='team1wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammatch',
            name='team2wins',
            field=models.IntegerField(default=0),
        ),
    ]
