# Generated by Django 5.1.4 on 2025-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0016_alter_playermatch_player1wins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.CharField(default='menS', max_length=255),
        ),
    ]
