# Generated by Django 5.1.4 on 2025-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0017_tournament_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='maxparti',
            field=models.IntegerField(default=6),
        ),
    ]
