# Generated by Django 5.1.4 on 2025-05-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0018_tournament_maxparti'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerholdPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmclub.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmclub.tournament')),
            ],
        ),
    ]
