# Generated by Django 5.1.4 on 2025-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0019_playerholdpool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
