# Generated by Django 5.1.4 on 2025-05-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0020_alter_tournament_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(default='menS', max_length=255),
        ),
    ]
