# Generated by Django 5.1.4 on 2025-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0021_alter_tournament_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
