# Generated by Django 5.1.4 on 2025-05-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmclub', '0022_court_alter_tournament_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court2Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateTimeField(blank=True, null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmclub.court')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmclub.tournament')),
            ],
        ),
    ]
